//
//  LFOPickerStyleKit.swift
//  AKSynthOne
//
//  Created by Matthew Fecher on 8/29/17.
//  Copyright © 2017 AudioKit. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class LFOPickerStyleKit : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawLFOWaveformPicker(fraction: CGFloat = 0) {
        //// Color Declarations
        let selected = UIColor(red: 0.902, green: 0.533, blue: 0.008, alpha: 1.000)
        let unselected = UIColor(red: 0.533, green: 0.533, blue: 0.533, alpha: 1.000)

        //// Variable Declarations
        let color1 = fraction <= 0.3 ? selected : unselected
        let color2 = fraction > 0.3 && fraction <= 0.6 ? selected : unselected
        let color3 = fraction > 0.6 && fraction <= 0.85 ? selected : unselected
        let color4 = fraction > 0.85 && fraction <= 1 ? selected : unselected

        //// background Drawing
        //let backgroundPath = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 215, height: 42))
        //color.setFill()
        //backgroundPath.fill()

        //// Square Drawing
        let squarePath = UIBezierPath()
        squarePath.move(to: CGPoint(x: 66.57, y: 22))
        squarePath.addLine(to: CGPoint(x: 66.57, y: 14))
        squarePath.addLine(to: CGPoint(x: 75.7, y: 14))
        squarePath.addLine(to: CGPoint(x: 75.7, y: 30))
        squarePath.addLine(to: CGPoint(x: 84.83, y: 30))
        squarePath.addLine(to: CGPoint(x: 84.83, y: 14))
        squarePath.addLine(to: CGPoint(x: 93.96, y: 14))
        squarePath.addLine(to: CGPoint(x: 93.96, y: 22))
        color2.setStroke()
        squarePath.lineWidth = 2
        squarePath.stroke()


        //// DownSaw Drawing
        let downSawPath = UIBezierPath()
        downSawPath.move(to: CGPoint(x: 172, y: 31))
        downSawPath.addLine(to: CGPoint(x: 172, y: 15))
        downSawPath.addLine(to: CGPoint(x: 185, y: 31))
        color4.setStroke()
        downSawPath.lineWidth = 2
        downSawPath.stroke()


        //// UpSaw Drawing
        let upSawPath = UIBezierPath()
        upSawPath.move(to: CGPoint(x: 135, y: 31))
        upSawPath.addLine(to: CGPoint(x: 135, y: 15))
        upSawPath.addLine(to: CGPoint(x: 122, y: 31))
        color3.setStroke()
        upSawPath.lineWidth = 2
        upSawPath.stroke()


        //// SineWave Drawing
        let sineWavePath = UIBezierPath()
        sineWavePath.move(to: CGPoint(x: 13, y: 20.93))
        sineWavePath.addCurve(to: CGPoint(x: 18, y: 13), controlPoint1: CGPoint(x: 13, y: 20.93), controlPoint2: CGPoint(x: 12, y: 13))
        sineWavePath.addCurve(to: CGPoint(x: 26, y: 30), controlPoint1: CGPoint(x: 24, y: 13), controlPoint2: CGPoint(x: 18, y: 30))
        sineWavePath.move(to: CGPoint(x: 39, y: 20.93))
        sineWavePath.addCurve(to: CGPoint(x: 34, y: 13), controlPoint1: CGPoint(x: 39, y: 20.93), controlPoint2: CGPoint(x: 40, y: 13))
        sineWavePath.addCurve(to: CGPoint(x: 26, y: 30), controlPoint1: CGPoint(x: 28, y: 13), controlPoint2: CGPoint(x: 34, y: 30))
        color1.setStroke()
        sineWavePath.lineWidth = 2
        sineWavePath.stroke()
    }

}
