//
//  MorphSelectorStyleKit.swift
//  SynthOne
//
//  Created by Aurelius Prochazka on 11/28/17.
//  Copyright © 2017 AudioKit. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class MorphSelectorStyleKit : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawMorphSelector(value: CGFloat = 1, width: CGFloat = 240, height: CGFloat = 53) {
        //// Color Declarations
        let selected = UIColor(red: 0.929, green: 0.533, blue: 0.000, alpha: 1.000)
        let unselected = UIColor(red: 0.533, green: 0.533, blue: 0.533, alpha: 1.000)
        let selectedBG = UIColor(red: 0.275, green: 0.271, blue: 0.278, alpha: 0.500)

        //// Variable Declarations
        let color1 = value <= 0.25 ? selected : unselected
        let color2 = value > 0.25 && value <= 0.5 ? selected : unselected
        let color3 = value > 0.5 && value <= 0.75 ? selected : unselected
        let color4 = value > 0.75 && value <= 1 ? selected : unselected
        let xValue: CGFloat = value * 0.79 * width + 6.0 / 260.0 * width

        //// Frames
        let frame = CGRect(x: 0, y: 0, width: width, height: height)


        //// background Drawing


        //// Chosen Area Drawing
        let chosenAreaPath = UIBezierPath(rect: CGRect(x: (xValue - 0.138461538462), y: 7, width: 39, height: 36))
        selectedBG.setFill()
        chosenAreaPath.fill()


        //// Triangle Drawing
        let trianglePath = UIBezierPath()
        trianglePath.move(to: CGPoint(x: frame.minX + 0.04309 * frame.width, y: frame.minY + 0.49057 * frame.height))
        trianglePath.addLine(to: CGPoint(x: frame.minX + 0.06625 * frame.width, y: frame.minY + 0.33962 * frame.height))
        trianglePath.addLine(to: CGPoint(x: frame.minX + 0.11258 * frame.width, y: frame.minY + 0.64151 * frame.height))
        trianglePath.addLine(to: CGPoint(x: frame.minX + 0.15120 * frame.width, y: frame.minY + 0.33962 * frame.height))
        trianglePath.addLine(to: CGPoint(x: frame.minX + 0.17822 * frame.width, y: frame.minY + 0.49057 * frame.height))
        color1.setStroke()
        trianglePath.lineWidth = 2
        trianglePath.stroke()


        //// Square Drawing
        let squarePath = UIBezierPath()
        squarePath.move(to: CGPoint(x: frame.minX + 0.31246 * frame.width, y: frame.minY + 0.49057 * frame.height))
        squarePath.addLine(to: CGPoint(x: frame.minX + 0.31246 * frame.width, y: frame.minY + 0.33962 * frame.height))
        squarePath.addLine(to: CGPoint(x: frame.minX + 0.35493 * frame.width, y: frame.minY + 0.33962 * frame.height))
        squarePath.addLine(to: CGPoint(x: frame.minX + 0.35493 * frame.width, y: frame.minY + 0.64151 * frame.height))
        squarePath.addLine(to: CGPoint(x: frame.minX + 0.39740 * frame.width, y: frame.minY + 0.64151 * frame.height))
        squarePath.addLine(to: CGPoint(x: frame.minX + 0.39740 * frame.width, y: frame.minY + 0.33962 * frame.height))
        squarePath.addLine(to: CGPoint(x: frame.minX + 0.43987 * frame.width, y: frame.minY + 0.33962 * frame.height))
        squarePath.addLine(to: CGPoint(x: frame.minX + 0.43987 * frame.width, y: frame.minY + 0.49057 * frame.height))
        color2.setStroke()
        squarePath.lineWidth = 2
        squarePath.stroke()


        //// HighPWMValue Drawing
        let highPWMValuePath = UIBezierPath()
        highPWMValuePath.move(to: CGPoint(x: frame.minX + 0.59591 * frame.width, y: frame.minY + 0.48169 * frame.height))
        highPWMValuePath.addLine(to: CGPoint(x: frame.minX + 0.59591 * frame.width, y: frame.minY + 0.33962 * frame.height))
        highPWMValuePath.addLine(to: CGPoint(x: frame.minX + 0.61908 * frame.width, y: frame.minY + 0.33962 * frame.height))
        highPWMValuePath.addLine(to: CGPoint(x: frame.minX + 0.61908 * frame.width, y: frame.minY + 0.64151 * frame.height))
        highPWMValuePath.addLine(to: CGPoint(x: frame.minX + 0.66155 * frame.width, y: frame.minY + 0.64151 * frame.height))
        highPWMValuePath.addLine(to: CGPoint(x: frame.minX + 0.66155 * frame.width, y: frame.minY + 0.33962 * frame.height))
        highPWMValuePath.addLine(to: CGPoint(x: frame.minX + 0.68471 * frame.width, y: frame.minY + 0.33962 * frame.height))
        highPWMValuePath.addLine(to: CGPoint(x: frame.minX + 0.68471 * frame.width, y: frame.minY + 0.48169 * frame.height))
        color3.setStroke()
        highPWMValuePath.lineWidth = 2
        highPWMValuePath.stroke()


        //// Sawtooth Drawing
        let sawtoothPath = UIBezierPath()
        sawtoothPath.move(to: CGPoint(x: frame.minX + 0.82504 * frame.width, y: frame.minY + 0.49057 * frame.height))
        sawtoothPath.addLine(to: CGPoint(x: frame.minX + 0.85979 * frame.width, y: frame.minY + 0.33962 * frame.height))
        sawtoothPath.addLine(to: CGPoint(x: frame.minX + 0.85979 * frame.width, y: frame.minY + 0.64151 * frame.height))
        sawtoothPath.addLine(to: CGPoint(x: frame.minX + 0.92542 * frame.width, y: frame.minY + 0.33962 * frame.height))
        sawtoothPath.addLine(to: CGPoint(x: frame.minX + 0.92542 * frame.width, y: frame.minY + 0.64151 * frame.height))
        sawtoothPath.addLine(to: CGPoint(x: frame.minX + 0.96635 * frame.width, y: frame.minY + 0.49057 * frame.height))
        color4.setStroke()
        sawtoothPath.lineWidth = 2
        sawtoothPath.stroke()
    }

}
