//
//  LfoBtnStyleKit.swift
//  AudioKitSynthOne
//
//  Created by Matthew Fecher on 7/28/17.
//  Copyright © 2017 AudioKit. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class LfoBtnStyleKit : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawLfoButton(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 106, height: 38), resizing: ResizingBehavior = .aspectFit, lfoSelected: CGFloat = 2, buttonText: String = "Hello") {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 106, height: 38), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 106, y: resizedFrame.height / 38)


        //// Color Declarations
        let lfo1Color = UIColor(red: 0.369, green: 0.369, blue: 0.388, alpha: 1.000)
        let lfo2Color = UIColor(red: 0.369, green: 0.369, blue: 0.388, alpha: 1.000)
        let offColor = UIColor(red: 0.180, green: 0.180, blue: 0.200, alpha: 1.000)
        let btnBack = UIColor(red: 0.243, green: 0.243, blue: 0.263, alpha: 1.000)
        let textColor = UIColor(red: 0.855, green: 0.855, blue: 0.855, alpha: 1.000)

        //// Variable Declarations
        let indicator1Color = lfoSelected == 1 ? lfo1Color : offColor
        let indicator2Color = lfoSelected == 2 ? lfo2Color : offColor

        //// Button
        //// btnBackground Drawing
        let btnBackgroundRect = CGRect(x: 2.5, y: 2.5, width: 100, height: 32)
        let btnBackgroundPath = UIBezierPath(roundedRect: btnBackgroundRect, cornerRadius: 2)
        btnBack.setFill()
        btnBackgroundPath.fill()
        UIColor.black.setStroke()
        btnBackgroundPath.lineWidth = 1
        btnBackgroundPath.stroke()
        let btnBackgroundStyle = NSMutableParagraphStyle()
        btnBackgroundStyle.alignment = .center
        let btnBackgroundFontAttributes = [
            NSFontAttributeName: UIFont(name: "AvenirNextCondensed-Regular", size: 16)!,
            NSForegroundColorAttributeName: textColor,
            NSParagraphStyleAttributeName: btnBackgroundStyle,
        ]

        let btnBackgroundTextHeight: CGFloat = buttonText.boundingRect(with: CGSize(width: btnBackgroundRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: btnBackgroundFontAttributes, context: nil).height
        context.saveGState()
        context.clip(to: btnBackgroundRect)
        buttonText.draw(in: CGRect(x: btnBackgroundRect.minX, y: btnBackgroundRect.minY + (btnBackgroundRect.height - btnBackgroundTextHeight) / 2, width: btnBackgroundRect.width, height: btnBackgroundTextHeight), withAttributes: btnBackgroundFontAttributes)
        context.restoreGState()


        //// Lfo2Indicator Drawing
        let lfo2IndicatorPath = UIBezierPath(rect: CGRect(x: 83, y: 8, width: 12, height: 20))
        indicator2Color.setFill()
        lfo2IndicatorPath.fill()


        //// Lfo1Indicator Drawing
        let lfo1IndicatorPath = UIBezierPath(rect: CGRect(x: 10, y: 8, width: 12, height: 20))
        indicator1Color.setFill()
        lfo1IndicatorPath.fill()
        
        context.restoreGState()

    }




    @objc(LfoBtnStyleKitResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
