platform :ios, '9.0'
use_frameworks!

def available_pods
    pod 'Disk', '~> 0.3.2'
    pod 'Audiobus'
end

target 'AudioKitSynthOne' do
    available_pods 
end

# target 'SynthOne' do
#     available_pods 
# end